version: 2
   
jobs:
  build:
    docker:
      - image: python:3.5.2
    working_directory: ~/code
    steps:
      - checkout

      - setup_remote_docker

      - run: |
        ./build_frontend.sh



