version: '2'
services:
  db:
    image: postgres
  web:
    env_file: .env
    build: ./backend_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend_api:/code
    # ports:
      # - "8000:8000"
    expose: 
      - "8000"
    depends_on:
      - db
  nginx:
    image: nginx
    build: ./frontend
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - ./frontend/nginx_conf:/etc/nginx
    depends_on:
      - web
    command: nginx -c /etc/nginx/nginx.conf -g "daemon off;"

