import os
import sys

_SELF_DIR = os.path.dirname(os.path.abspath(__file__))
template = '''"""
This is autogenerated from %s
"""
from docker_wp.configs.%s import *
'''


def rel_path(path):
    return os.path.join(_SELF_DIR, path)


def write_settings_file(env):
    with open(rel_path('../settings.py'), "w+") as settings:
        settings.write(template % (__file__, env))


def write_all():
    write_settings_file(sys.argv[1])


if __name__ == '__main__':
    write_all()